### ISSUE TITLE
请教下几个问题

### ISSUE THREAD

**Issue by lonelyclick** [x6doooo/GeoMap#4]
看了您的GeoMap项目，受益匪浅，但是有几个不明白的地方，望指教一下：
1.不知这个的地图数据从哪里来的呢，还有里面的cp，是怎么计算出来的，还是手工绘制出来的。
2.代码中
"formatPoint": function(p){
    return [
      (p[0] < -168.5 ? p[0] + 360 : p[0]) + 170,
      90 - p[1]
    ];
  }
为什么要将点做这样的处理呢？基于什么原理呢？

**Comment by Jeffiy** [comment]
请问这个有些什么事件呢？比如基本的点击事件？没找到在哪呢

**Comment by x6doooo** [comment]
@Jeffiy svg元素和普通的html dom元素的事件是一样的 ，   这个项目是用raphael绘制svg的，也可以用raphael的事件接口
